name: gh release create
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true
concurrency: ${{ github.workflow }}
jobs:
  gm:
    uses: ./.github/workflows/gm.yml
    secrets: inherit
  gh-release-create:
    needs: gm
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      # compress each "x86_64-linux-unknown-gnu" directory into a tar/zip file
      - run: |
          for f in *; do
            if [[ $f == *"-windows-"* ]]; then
              zip -r "$f.zip" "$f"
            else
              tar -czf "$f.tar.gz" "$f"
            fi
            rm -rf "$f"
          done
      - run: |
          gh release create "v$VERSION" --generate-notes \
            *.tar.gz *.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
