name: gm
on:
  push:
    branches: ["main"]
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/gm.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - .github/**
      - "!.github/workflows/gm.yml"
  workflow_call:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  gm:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux-unknown-gnu
            gen: x64.release
          # - os: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   gen: x64.release
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          #   gen: x64.release
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: ./setup-depot_tools
      - run: fetch v8
      - run: gclient sync --revision "v8@$(cat v8-tag.txt)"
      - if: runner.os == 'Linux'
        run: ./build/install-build-deps.sh
        working-directory: v8
      - run: |
          # tools/dev/gm.py
          tools/dev/v8gen.py "$GEN"
          ninja -C out.gn/"$GEN" v8
        env:
          GEN: ${{ matrix.gen }}
        working-directory: v8
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: v8/out.gn
